# Generated by Django 5.1.2 on 2026-01-31 18:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="General", max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("expense_date", models.DateField(default=datetime.date.today)),
                (
                    "receipt_image",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("currency", models.CharField(blank=True, default="INR", max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlannedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Planned Expense", max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("due_date", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=100)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "🇮🇳 INR - Indian Rupee (₹)"),
                            ("USD", "🇺🇸 USD - US Dollar ($)"),
                            ("EUR", "🇪🇺 EUR - Euro (€)"),
                            ("GBP", "🇬🇧 GBP - British Pound (£)"),
                            ("JPY", "🇯🇵 JPY - Japanese Yen (¥)"),
                            ("AUD", "🇦🇺 AUD - Australian Dollar (A$)"),
                            ("CAD", "🇨🇦 CAD - Canadian Dollar (C$)"),
                            ("CNY", "🇨🇳 CNY - Chinese Yuan (¥)"),
                            ("AED", "🇦🇪 AED - UAE Dirham (د.إ)"),
                            ("SAR", "🇸🇦 SAR - Saudi Riyal (﷼)"),
                            ("RUB", "🇷🇺 RUB - Russian Ruble (₽)"),
                            ("KRW", "🇰🇷 KRW - South Korean Won (₩)"),
                            ("BRL", "🇧🇷 BRL - Brazilian Real (R$)"),
                            ("PKR", "🇵🇰 PKR - Pakistani Rupee (₨)"),
                            ("BDT", "🇧🇩 BDT - Bangladeshi Taka (৳)"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "target_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
