# Generated by Django 5.1.2 on 2026-03-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_debt_shoppingitem_warranty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="warranty",
            name="user",
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
        migrations.DeleteModel(
            name="ShoppingItem",
        ),
        migrations.DeleteModel(
            name="Warranty",
        ),
    ]
